#!/usr/bin/env node
/*
 * Turn the committed markdown in content/posts into the module the application and the
 * prerenderer both read.
 *
 * This runs before vite. Markdown is rendered here, at build time, in Node, which means
 * the browser never ships a markdown parser and, more importantly, that the sanitising
 * renderer is the only path from an author's keystrokes to published HTML.
 *
 * Any problem at all stops the build. A blog that silently drops an article it could
 * not parse is worse than a build that goes red, because nobody finds out.
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, copyFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import sharp from 'sharp'

import { parsePostFile } from '../src/content/postFile.js'
import { buildCollection } from '../src/content/collection.js'
import { renderMarkdown, readingTimeMinutes } from '../src/content/markdown.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const postsDir = join(root, 'content/posts')
const mediaDir = join(root, 'public/blog-media')
const generatedDir = join(root, 'src/generated')
const adminDir = join(root, 'public/admin')

function fail(message, details = []) {
  console.error(`\nbuild-content: ${message}`)
  for (const detail of details) console.error(`  - ${detail}`)
  console.error('')
  process.exit(1)
}

/** Intrinsic size of a hero image, so the social card and the layout both declare it. */
async function imageSize(publicPath) {
  const file = join(mediaDir, publicPath.replace('/blog-media/', ''))
  if (!existsSync(file)) return {}
  try {
    const { width, height } = await sharp(file).metadata()
    return { heroImageWidth: width || null, heroImageHeight: height || null }
  } catch {
    return {}
  }
}

async function main() {
  const files = existsSync(postsDir)
    ? readdirSync(postsDir)
        .filter((name) => name.endsWith('.md'))
        .sort()
    : []

  const parsed = []
  for (const name of files) {
    const path = `content/posts/${name}`
    try {
      parsed.push(parsePostFile(readFileSync(join(postsDir, name), 'utf8'), path))
    } catch (cause) {
      fail('a post file could not be read', [cause.message])
    }
  }

  const collection = buildCollection(parsed)
  if (collection.errors.length > 0) {
    fail(
      `${collection.errors.length} content problem(s); nothing was generated`,
      collection.errors.map((e) => `${e.kind}: ${e.message}`),
    )
  }
  for (const warning of collection.warnings) {
    console.warn(`build-content: warning: ${warning.message}`)
  }

  // Everything the browser and the prerenderer are allowed to see. The raw markdown
  // body is deliberately left out: only the rendered, sanitised HTML ships.
  const posts = []
  for (const post of collection.posts) {
    posts.push({
      id: post.id,
      slug: post.slug,
      title: post.title,
      excerpt: post.excerpt,
      author: post.author || 'Homezai Team',
      publishedAt: post.publishedAt,
      updatedAt: post.updatedAt || post.publishedAt,
      heroImage: post.heroImage,
      heroImageAlt: post.heroImageDecorative ? '' : post.heroImageAlt || '',
      heroImageDecorative: Boolean(post.heroImageDecorative),
      ...(await imageSize(post.heroImage || '')),
      seoTitle: post.seoTitle || null,
      seoDescription: post.seoDescription || null,
      tags: Array.isArray(post.tags) ? post.tags : [],
      featured: Boolean(post.featured),
      featureOrder: Number.isInteger(post.featureOrder) ? post.featureOrder : null,
      readingMinutes: readingTimeMinutes(post.body),
      bodyHtml: renderMarkdown(post.body),
    })
  }

  const featuredSlugs = new Set(collection.featured.map((p) => p.slug))
  const featured = posts.filter((p) => featuredSlugs.has(p.slug))
  featured.sort(
    (a, b) => collection.featured.findIndex((p) => p.slug === a.slug) - collection.featured.findIndex((p) => p.slug === b.slug),
  )

  mkdirSync(generatedDir, { recursive: true })
  writeFileSync(
    join(generatedDir, 'content.js'),
    `/* Generated by scripts/build-content.mjs. Do not edit by hand. */\n` +
      `export const posts = ${JSON.stringify(posts, null, 2)}\n\n` +
      `export const featuredPosts = ${JSON.stringify(featured, null, 2)}\n\n` +
      `export const redirects = ${JSON.stringify(collection.redirects, null, 2)}\n`,
    'utf8',
  )

  // The editor bundle is served from homezai.com, not from a third party CDN, because
  // a page that handles a GitHub token should not fetch its own code from a host we do
  // not control. The version is whatever package-lock.json pins.
  mkdirSync(adminDir, { recursive: true })
  const cmsBundle = join(root, 'node_modules/@sveltia/cms/dist/sveltia-cms.js')
  if (!existsSync(cmsBundle)) fail('the Sveltia CMS bundle is not installed; run npm ci')
  copyFileSync(cmsBundle, join(adminDir, 'sveltia-cms.js'))
  copyFileSync(join(root, 'src/content/revisions.js'), join(adminDir, 'revisions.js'))

  console.log(
    `build-content: ${posts.length} published article(s), ${featured.length} featured, ${collection.redirects.length} redirect(s)`,
  )
}

main().catch((error) => fail(error.stack || String(error)))
